src/objects/Kombucha_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Kombucha Configuration Data.</description>
    
    <!-- default settings -->
     <fields>
        <fullName>Hour__c</fullName>
        <label>Hour</label>
        <length>10</length>
        <type>Text</type>
        <defaultValue>'4'</defaultValue>
    </fields>
    <fields>
        <fullName>Minute__c</fullName>
        <label>Minute</label>
        <length>10</length>
        <type>Text</type>
        <defaultValue>'0'</defaultValue>
    </fields>

    <fields>
        <fullName>CronJobId_SlackPoster__c</fullName>
        <label>Cron Job Id for SlackPoster</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CronJobName_SlackPoster__c</fullName>
        <label>Cron Job Name for SlackPoster</label>
        <length>40</length>
        <type>Text</type>
    </fields>

    <!-- general settings -->


    <!-- search settings -->

    <!-- apexclass settings -->

    <!-- email settings -->
    

    <label>Kombucha Configuration</label>
</CustomObject>

src/classes/KombuchaSlackPoster.cls
global with sharing class KombuchaSlackPoster implements Schedulable{
	global void execute(SchedulableContext SC) {
        doExecute();
    }
    
    @future (callout=true)
    public static void doExecute(){
        postToSlack();
    }

    public static void createDailyScheduledJob(){
		Kombucha_Configuration__c kombuchaConfig = Kombucha_Configuration__c.getInstance(KombuchaConstants.CUSTOM_SETTING_NAME);
		
		if(kombuchaConfig == null){
			return;
		}

        KombuchaSlackPoster ksp = new KombuchaSlackPoster();  
 		
 		//String sch = String.format('0 {0} {1} * * ?', new String[] {kombuchaConfig.Minute__c, kombuchaConfig.Hour__c});
        string sch = '0 58 14 * * ?'; 
        Id cronId = System.schedule('Kombucha - Slack Poster',sch,ksp);

        kombuchaConfig.CronJobId_SlackPoster__c = cronId;
        kombuchaConfig.CronJobName_SlackPoster__c = 'Kombucha - Slack Poster';
        update kombuchaConfig;
    }

    public static void postToSlack(){
    	
    }

}