src/objects/Kombucha_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Kombucha Configuration Data.</description>
    
    <!-- default settings -->
    <fields>
        <fullName>Instance_URL__c</fullName>
        <label>Instance URL</label>
        <length>80</length>
        <type>Text</type>
    </fields>


    <!-- general settings -->
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Security_Code__c</fullName>
        <label>Security Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>


    <!-- search settings -->
    <fields>
        <fullName>Query1__c</fullName>
        <label>Query 1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query1_Position__c</fullName>
        <label>Query1 Position</label>
        <length>10</length>
        <type>Text</type>
    </fields>

    <!-- apexclass settings -->
    <fields>
        <fullName>ApexClass_Query1__c</fullName>
        <label>ApexClass Query 1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ApexClass_Query1_Position__c</fullName>
        <label>ApexClass Query1 Position</label>
        <length>10</length>
        <type>Text</type>
    </fields>

    <!-- email settings -->
    <fields>
        <fullName>Recipient__c</fullName>
        <label>Recipient</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Add_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Add Date</label>
        <type>Checkbox</type>
    </fields>
    

    <label>Kombucha Configuration</label>
</CustomObject>

src/classes/TestKombuchaSettingSetup.cls
@isTest
private class TestKombuchaSettingSetup {
	
	@isTest static void test_isSchedulerAvailable(){
		//scenario 1: there is no custom setting
		System.assertEquals(KombuchaSettingSetup.isSchedulerAvailable().contains('Kombucha custom setting is not available.'), true);

		//scenario 2: there is custom setting, but certain fields are null
		Kombucha_Configuration__c kombuchaConfig = new Kombucha_Configuration__c();
		kombuchaConfig.Name = KombuchaConstants.CUSTOM_SETTING_NAME;
		insert kombuchaConfig;
		System.assertEquals(KombuchaSettingSetup.isSchedulerAvailable().contains('Please go to SETTINGS page to complete configuration first.'), true);
		
		//scenario 3: custom setting has all required data filled in, and check username and password
		kombuchaConfig.Instance_URL__c = 'dummyData';
		kombuchaConfig.Username__c = 'dummyData';
		kombuchaConfig.Password__c = 'dummyData';
		kombuchaConfig.Security_Code__c = 'dummyData';
		kombuchaConfig.Query1__c = 'dummyData';
		kombuchaConfig.ApexClass_Query1__c = 'dummyData';
		kombuchaConfig.Query1_Position__c = 'dummyData';
		kombuchaConfig.ApexClass_Query1_Position__c = 'dummyData';
		kombuchaConfig.Recipient__c = 'dummyData';
		kombuchaConfig.Title__c = 'dummyData';
		kombuchaConfig.Add_Date__c = true;
		update kombuchaConfig;

		System.assertEquals(KombuchaSettingSetup.isSchedulerAvailable(), '{"statusMessage":"","status":"ok","result":[]}');
	}

	@isTest static void test_saveConfigData(){
		Kombucha_Configuration__c kombuchaConfig = new Kombucha_Configuration__c();
		kombuchaConfig.Name = KombuchaConstants.CUSTOM_SETTING_NAME;
		insert kombuchaConfig;

		System.assertEquals(KombuchaSettingSetup.saveConfigData(KombuchaConstants.KOMBUCHA_SETTINGSETUP_SAVECONFIG), '{"statusMessage":"","status":"ok","result":[]}');
	}

	@isTest static void test_getConfigData(){
		Kombucha_Configuration__c kombuchaConfig = new Kombucha_Configuration__c();
		kombuchaConfig.Name = KombuchaConstants.CUSTOM_SETTING_NAME;
		insert kombuchaConfig;
		KombuchaSettingSetup.saveConfigData(KombuchaConstants.KOMBUCHA_SETTINGSETUP_SAVECONFIG);
		KombuchaSettingSetup.getConfigData();
		System.assert(true);
	}
}