src/objects/Kombucha_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Kombucha Configuration Data.</description>
    
    <!-- default settings -->
    <fields>
        <fullName>CodeCoverage__c</fullName>
        <label>Code Coverage</label>
        <length>10</length>
        <type>Text</type>
    </fields>


    <!-- general settings -->


    <!-- search settings -->

    <!-- apexclass settings -->

    <!-- email settings -->
    <fields>
        <fullName>Slack_Endpoint__c</fullName>
        <label>Slack Endpoint</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Slack_Request__c</fullName>
        <label>Slack Request</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    

    <label>Kombucha Configuration</label>
</CustomObject>

src/classes/TestKombuchaSlackPoster.cls
@isTest
private class TestKombuchaSlackPoster {
	
	@isTest static void test_createDailyScheduledJob() {
		Kombucha_Configuration__c kombuchaConfig = new Kombucha_Configuration__c();
		kombuchaConfig.Name = KombuchaConstants.CUSTOM_SETTING_NAME;
		insert kombuchaConfig;
		KombuchaSettingSetup.saveConfigData(KombuchaConstants.KOMBUCHA_SETTINGSETUP_SAVECONFIG);

		Test.startTest();
		kombuchaConfig = Kombucha_Configuration__c.getInstance(KombuchaConstants.CUSTOM_SETTING_NAME);
		kombuchaConfig.CodeCoverage__c = 'dummyData';
		kombuchaConfig.Slack_Request__c = 'dummyData';
		kombuchaConfig.Slack_Endpoint__c = 'dummyData';
		update kombuchaConfig;
		KombuchaSlackPoster.createDailyScheduledJob();
		Test.stopTest();
	}
	
}